export const CurtainData = {
    items: [
        { id: 1, src: '/public/theme/images/curtain-image-1.webp', color: 'red' },
        { id: 2, src: '/public/theme/images/curtain-image-2.webp', color: 'red' },
        { id: 3, src: '/public/theme/images/curtain-image-3.webp', color: 'purple' },
        { id: 4, src: '/public/theme/images/curtain-image-4.webp', color: 'purple' },
        { id: 5, src: '/public/theme/images/curtain-image-5.webp', color: 'pink' },
        { id: 6, src: '/public/theme/images/curtain-image-6.webp', color: 'pink' },
        { id: 7, src: '/public/theme/images/curtain-image-7.webp', color: 'brown' },
        { id: 8, src: '/public/theme/images/curtain-image-8.webp', color: 'brown' },
        { id: 9, src: '/public/theme/images/curtain-image-9.webp', color: 'dark-green' },
        { id: 11, src: '/public/theme/images/curtain-image-11.webp', color: 'pale-blue' },
        { id: 12, src: '/public/theme/images/curtain-image-12.webp', color: 'pale-blue' },
        { id: 13, src: '/public/theme/images/curtain-image-13.webp', color: 'pale-purple' },
        { id: 14, src: '/public/theme/images/curtain-image-14.webp', color: 'pale-purple' },
        { id: 15, src: '/public/theme/images/curtain-image-15.webp', color: 'orange' },
        { id: 16, src: '/public/theme/images/curtain-image-16.webp', color: 'orange' },
        { id: 17, src: '/public/theme/images/curtain-image-17.webp', color: 'pale-green' },
        { id: 18, src: '/public/theme/images/curtain-image-18.webp', color: 'pale-green' },
        { id: 19, src: '/public/theme/images/curtain-image-19.webp', color: 'green' },
        { id: 20, src: '/public/theme/images/curtain-image-20.webp', color: 'green' },
    ],
};
