export const CircleData = {
    items: [
        { id: 1, src: '/public/theme/images/loader_anim-1.webp', color: 'pale-green' },
        { id: 2, src: '/public/theme/images/loader_anim-2.webp', color: 'green' },
        { id: 3, src: '/public/theme/images/loader_anim-3.webp', color: 'red' },
        { id: 4, src: '/public/theme/images/loader_anim-4.webp', color: 'red' },
        { id: 5, src: '/public/theme/images/loader_anim-5.webp', color: 'purple' },
        { id: 6, src: '/public/theme/images/loader_anim-6.webp', color: 'purple' },
        { id: 7, src: '/public/theme/images/loader_anim-7.webp', color: 'pink' },
        { id: 8, src: '/public/theme/images/loader_anim-8.webp', color: 'pink' },
        { id: 9, src: '/public/theme/images/loader_anim-9.webp', color: 'brown' },
        { id: 10, src: '/public/theme/images/loader_anim-10.webp', color: 'brown' },
        { id: 11, src: '/public/theme/images/loader_anim-11.webp', color: 'dark-green' },
        { id: 12, src: '/public/theme/images/loader_anim-12.webp', color: 'dark-green' },
        { id: 13, src: '/public/theme/images/loader_anim-13.webp', color: 'pale-blue' },
        { id: 14, src: '/public/theme/images/loader_anim-14.webp', color: 'pale-blue' },
        { id: 15, src: '/public/theme/images/loader_anim-15.webp', color: 'pale-purple' },
        { id: 16, src: '/public/theme/images/loader_anim-16.webp', color: 'pale-purple' },
        { id: 17, src: '/public/theme/images/loader_anim-17.webp', color: 'orange' },
        { id: 18, src: '/public/theme/images/loader_anim-18.webp', color: 'orange' },
        { id: 19, src: '/public/theme/images/loader_anim-19.webp', color: 'pale-green' },
        { id: 20, src: '/public/theme/images/loader_anim-20.webp', color: 'green' },
    ],
};
