export const mapStyles = {
    // Caro De Robertis
    pink: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#dcbab2',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#396559',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'rgba(33, 53, 49, 0.8)',
                'scrub',
                'hsla(161, 50%, 18%, 0.6)',
                'agriculture',
                'rgba(43, 68, 61, 0.6)',
                'park',
                '#396559',
                'grass',
                'rgba(43, 68, 61, 0.6)',
                'cemetery',
                'rgb(69, 115, 102)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'rgb(52, 116, 88)',
                'sand',
                'rgb(48, 38, 74)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'rgba(1, 1, 2, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'rgba(1, 1, 2, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#2c5846',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#6b9e82',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(147, 21%, 39%)',
                'hsl(147, 21%, 42%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(147, 21%, 39%)',
                'hsl(147, 21%, 42%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#558269',
        },
    ],

    // Denice Frohman
    brown: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // Natalie Diaz
    orange: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#c85c19',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#d0a49a',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(11, 37%, 75%)',
                'hsl(11, 37%, 78%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(11, 37%, 75%)',
                'hsl(11, 37%, 78%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#dcbab2',
        },
    ],

    // Eve Ewing
    paleBlue: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#5d7c8e',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#c85c19',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(23, 61%, 37%, 0.87)',
                'scrub',
                'hsla(23, 78%, 44%, 0.72)',
                'agriculture',
                'hsla(23, 78%, 44%, 0.64)',
                'park',
                'hsl(23, 78%, 44%)',
                'grass',
                'hsl(23, 59%, 34%)',
                'cemetery',
                'hsl(23, 78%, 44%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(23, 82%, 55%)',
                'sand',
                'hsl(257, 32%, 22%)',
                'hsl(267, 13%, 14%)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'rgba(1, 1, 2, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'rgba(1, 1, 2, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#974e21',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#e5742e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(23, 78%, 41%)',
                'hsl(23, 78%, 44%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(23, 78%, 41%)',
                'hsl(23, 78%, 44%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#c85c19',
        },
    ],

    // Caleb Gayle
    purple: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#d54134',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#d54134',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(5, 66%, 52%, 0.83)',
                'scrub',
                'hsla(5, 66%, 52%, 0.67)',
                'agriculture',
                'hsla(5, 66%, 52%, 0.67)',
                'park',
                'hsl(5, 66%, 52%)',
                'grass',
                'hsl(5, 60%, 43%)',
                'cemetery',
                'hsl(5, 66%, 52%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(5, 73%, 60%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#af372c',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#eaaa2a',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(40, 82%, 58%)',
                'hsl(40, 82%, 61%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(40, 82%, 58%)',
                'hsl(40, 82%, 61%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#edb74a',
        },
    ],

    // Robin Coste Lewis
    green: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#558269',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // April Reign
    default: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#d54134',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#016559',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(173, 98%, 20%, 0.82)',
                'scrub',
                'hsla(173, 98%, 20%, 0.63)',
                'agriculture',
                'hsla(173, 98%, 20%, 0.63)',
                'park',
                'hsl(173, 98%, 20%)',
                'grass',
                'hsl(173, 93%, 14%)',
                'cemetery',
                'hsl(173, 98%, 20%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(173, 96%, 25%)',
                'sand',
                'rgb(48, 38, 74)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'rgba(1, 1, 2, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'rgba(1, 1, 2, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#015047',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#269bdf',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(202, 74%, 38%)',
                'hsl(202, 74%, 41%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#1b7db6',
        },
    ],

    // Ellery Washington
    darkGreen: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#016559',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#e5742e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(23, 78%, 41%)',
                'hsl(23, 78%, 44%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(23, 78%, 41%)',
                'hsl(23, 78%, 44%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#c85c19',
        },
    ],

    // Renee Watson
    paleGreen: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#9aa593',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#edb74a',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(40, 82%, 61%, 0.81)',
                'scrub',
                'hsla(40, 82%, 61%, 0.62)',
                'agriculture',
                'hsla(40, 82%, 61%, 0.6)',
                'park',
                'hsla(40, 73%, 60%, 0.86)',
                'grass',
                'hsl(40, 80%, 34%)',
                'cemetery',
                'hsl(40, 82%, 61%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(40, 82%, 61%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#bc8a24',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // Jenna Wortham
    palePurple: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#786887',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#016559',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(173, 98%, 20%, 0.82)',
                'scrub',
                'hsla(173, 98%, 20%, 0.63)',
                'agriculture',
                'hsla(173, 98%, 20%, 0.63)',
                'park',
                'hsl(173, 98%, 20%)',
                'grass',
                'hsl(173, 93%, 14%)',
                'cemetery',
                'hsl(173, 98%, 20%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(173, 96%, 25%)',
                'sand',
                'rgb(48, 38, 74)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'rgba(1, 1, 2, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'rgba(1, 1, 2, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#015047',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],
};
