export const mapStyles = {
    // Caro De Robertis
    pink: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#e5d1cc',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#261f2e',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsl(268, 16%, 16%)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0)',
                'park',
                'hsl(268, 16%, 16%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(268, 16%, 16%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#9183a0',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(270, 13%, 44%)',
                'hsl(270, 13%, 47%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(270, 13%, 44%)',
                'hsl(270, 13%, 47%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#786887',
        },
    ],

    // Denice Frohman
    brown: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // Natalie Diaz
    orange: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // Eve Ewing
    paleBlue: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // Caleb Gayle
    purple: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // Robin Coste Lewis
    green: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // April Reign
    default: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // Ellery Washington
    darkGreen: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // Renee Watson
    paleGreen: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],

    // Jenna Wortham
    palePurple: [
        {
            name: 'building-extrusion',
            type: 'fill-extrusion-color',
            color: '#b79257',
        },
        {
            name: 'national-park',
            type: 'fill-color',
            color: '#5d3088',
        },
        {
            name: 'landuse',
            type: 'fill-color',
            color: [
                'match',
                ['get', 'class'],
                'wood',
                'hsla(271, 56%, 25%, 0.76)',
                'scrub',
                'hsla(271, 48%, 36%, 0.59)',
                'agriculture',
                'hsla(271, 48%, 36%, 0.59)',
                'park',
                'hsl(271, 48%, 36%)',
                'grass',
                'hsl(271, 46%, 23%)',
                'cemetery',
                'hsl(271, 36%, 34%)',
                'glacier',
                'rgb(234, 234, 234)',
                'pitch',
                'hsl(271, 56%, 45%)',
                'sand',
                'hsl(257, 35%, 26%)',
                'rgb(35, 31, 40)',
            ],
        },
        {
            name: 'hillshade',
            type: 'fill-color',
            color: [
                'interpolate',
                ['linear'],
                ['zoom'],
                14,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0.06)',
                    'rgba(98, 80, 118, 0.12)',
                ],
                16,
                [
                    'match',
                    ['get', 'class'],
                    'shadow',
                    'hsla(268, 34%, 1%, 0)',
                    'rgba(98, 80, 118, 0)',
                ],
            ],
        },
        {
            name: 'pitch-outline',
            type: 'line-color',
            color: '#4b2d67',
        },
        {
            name: 'tunnel-simple',
            type: 'line-color',
            color: '#de695e',
        },
        {
            name: 'road-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'bridge-simple',
            type: 'line-color',
            color: [
                'match',
                ['get', 'class'],
                [
                    'primary_link',
                    'secondary_link',
                    'tertiary_link',
                    'street',
                    'street_limited',
                    'service',
                    'track',
                ],
                'hsl(5, 66%, 49%)',
                'hsl(5, 66%, 52%)',
            ],
        },
        {
            name: 'road-label-simple',
            type: 'text-halo-color',
            color: '#d54134',
        },
    ],
};
