on: 
  push:
    branches:
      - dev
   
jobs: 
  updates_repos: 
    runs-on: ubuntu-latest 
    steps: 
      - name: h7 master call
        run: | 
          curl -n -X PATCH "https://github.sunship.dev/?path=elder&token=${{secrets.H7_TOKEN}}&cache=true"